public class Main {
  public static void main(String[] args) {
    char c = 'A';
    c++;
    System.out.println(c);
    c += 2;
    System.out.println(c);
    System.out.println(c + 1);
    System.out.println((char) (c + 1));
    System.out.println('a' + 'b');
    System.out.println("" + 'a' + 'b');
    System.out.println('a' + 'b' + "c");
    System.out.println("c" + 'a' + 'b');
    System.out.println(1 + 2 + "3" + 4 + 5);
    System.out.println("x" + (1 + 2));
    System.out.println("val: " + 2.0 + " " + true + " " + 'q' + " " + 7L);
    char d = '7';
    System.out.println(d - '0');
    System.out.println(d);
    int code = 'a';
    System.out.println(code);
    String s = "Hello World";
    System.out.println(s.length());
    System.out.println(s.charAt(4));
    System.out.println(s.substring(6));
    System.out.println(s.substring(0, 5));
    System.out.println(s.indexOf('o'));
    System.out.println(s.indexOf("o", 5));
    System.out.println(s.lastIndexOf('o'));
    System.out.println(s.indexOf("xyz"));
    System.out.println(s.toUpperCase());
    System.out.println(s.toLowerCase());
    System.out.println(s.replace('l', 'L'));
    System.out.println(s.replace("World", "Java"));
    System.out.println(s.contains("lo W"));
    System.out.println(s.startsWith("Hell"));
    System.out.println(s.endsWith("d"));
    System.out.println("  pad me  ".trim() + "|");
    System.out.println("apple".compareTo("banana"));
    System.out.println("apple".compareTo("app"));
    System.out.println("Apple".compareTo("apple"));
    System.out.println("abc".compareTo("abc"));
    System.out.println("Java".equals("java"));
    System.out.println("Java".equalsIgnoreCase("java"));
    System.out.println("ab".repeat(3));
    System.out.println("".isEmpty());
    System.out.println("a,b,,c,,".split(",").length);
    String[] parts = "the quick  brown fox".split(" ");
    for (int i = 0; i < parts.length; i++) System.out.print("[" + parts[i] + "]");
    System.out.println();
    String[] ws = "  lots   of space ".trim().split("\\s+");
    System.out.println(ws.length + " " + ws[1]);
    char[] arr = "dcba".toCharArray();
    System.out.println(arr.length);
    System.out.println(arr);
    System.out.println(String.valueOf(arr));
    System.out.println(new String(arr));
    System.out.println(String.valueOf(3.0) + String.valueOf(true));
    System.out.println(Integer.parseInt("-42") + 1);
    System.out.println(Double.parseDouble("2.5") * 2);
    System.out.println(Character.isDigit('5') + " " + Character.isLetter('5') + " " + Character.isUpperCase('Q'));
    System.out.println(Character.toUpperCase('m'));
    System.out.println(Character.getNumericValue('8'));
    String a1 = "java";
    String a2 = "ja" + "va";
    String part = "ja";
    String a3 = part + "va";
    String a4 = new String("java");
    System.out.println(a1 == a2);
    System.out.println(a1 == a3);
    System.out.println(a1 == a4);
    System.out.println(a1.equals(a3));
    String acc = "";
    for (int i = 0; i < 5; i++) acc += i;
    System.out.println(acc);
    String t = "x";
    t += 1 + 2;
    System.out.println(t);
    System.out.println("tab\tsep" + "\\" + "\"q\"");
  }
}
