public class Main {
  public static void main(String[] args) {
    int big = 2147483647;
    big++;
    System.out.println(big);
    System.out.println(Integer.MAX_VALUE + 1);
    System.out.println(46341 * 46341);
    System.out.println(-7 / 2);
    System.out.println(-7 % 2);
    System.out.println(7 % -2);
    System.out.println(-4 % 2);
    System.out.println(5 / 2 * 2.0);
    System.out.println(5 / 2.0);
    System.out.println(1.0 / 3);
    System.out.println(10.0 / 4);
    System.out.println(100.0);
    System.out.println(1e7);
    System.out.println(12345678.9);
    System.out.println(0.001);
    System.out.println(0.0001);
    System.out.println(1.0 / 0);
    System.out.println(-1.0 / 0);
    System.out.println(0.0 / 0);
    System.out.println(0.1 + 0.2);
    System.out.println(3.0 * 1.1);
    System.out.println((int) 3.99);
    System.out.println((int) -3.99);
    System.out.println((int) 1e20);
    System.out.println((double) 7 / 2);
    System.out.println((double) (7 / 2));
    float f = 1.1f;
    System.out.println(f);
    System.out.println(f * 3);
    System.out.println(f + 0.1);
    float g = 10;
    System.out.println(g / 3);
    long L = 9000000000L;
    System.out.println(L * 2);
    System.out.println(L / 7);
    System.out.println(Long.MAX_VALUE + 1);
    long m = 100000 * 100000;
    System.out.println(m);
    long m2 = 100000L * 100000;
    System.out.println(m2);
    byte b = (byte) 200;
    System.out.println(b);
    short s = (short) 70000;
    System.out.println(s);
    char c = (char) 97;
    System.out.println(c);
    System.out.println((int) 'Z');
    System.out.println(Math.round(2.5));
    System.out.println(Math.round(-2.5));
    System.out.println(Math.round(2.4f));
    System.out.println(Math.pow(2, 10));
    System.out.println(Math.sqrt(2));
    System.out.println(Math.abs(-7));
    System.out.println(Math.abs(-7.5));
    System.out.println(Math.max(3, 7.0));
    System.out.println(Math.min(-2, 5));
    System.out.println(Math.floor(-2.5));
    System.out.println(Math.ceil(2.1));
    System.out.println(7 >> 1);
    System.out.println(-7 >> 1);
    System.out.println(-7 >>> 28);
    System.out.println(5 & 3);
    System.out.println(5 | 3);
    System.out.println(5 ^ 3);
    System.out.println(~5);
    System.out.println(1 << 31);
    System.out.println(123456789.0 * 1000);
    System.out.println(0.5 * 3);
    System.out.println(2.0E-5 * 3);
    System.out.println(1234567.0);
    System.out.println(9999999.0);
    System.out.println(-0.0);
  }
}
